services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: notes_db
      POSTGRES_USER: notes_user
      POSTGRES_PASSWORD: secretpassword
    depends_on:
      - db
    command: >
      sh -c "
        until PGPASSWORD=$$POSTGRES_PASSWORD psql -h $$POSTGRES_HOST -p $$POSTGRES_PORT -U $$POSTGRES_USER -d $$POSTGRES_DB -c 'SELECT 1'; do
          echo 'Waiting for Postgres…';
          sleep 2;
        done;
        python manage.py migrate --noinput;
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  postgres_data: